### ISSUE TITLE
recursion:

### ISSUE THREAD

**Issue by svMahler** [MaddnRuleZ/Tree#15]
recursion:

doc1:
parsen start
. . .
input statement -> parse doc 2 full, return root of doc 2
add root of doc 2 zu tree of doc 1
continue parsing doc 1
. . . .

_Originally posted by @MaddnRuleZ in https://github.com/MaddnRuleZ/Tree/issues/12#issuecomment-1632583431_

Meinst du damit, dass input eine eigenes Objekt root hat, oder dass die Klasse input quasi als Root fungiert.

**Comment by MaddnRuleZ** [comment]
Wenn input registriert wird wird ein komplett neuer Parser aufgerufen (mit neuer url usw), dieser hat ja Rückgabewert Root. Die Root des Neuen Docs wird dann in den Baum gehangen an der aktuellen stelle. Unter anderem um auch im Front raus und rein schieben zwischen documenten möglich zu machen.

**Comment by svMahler** [comment]
Und was ist mit dem Zeug, das am Anfang vom Hauptdokument steht, die Input Datei hat das nicht und hat auch kein beginDocument, woher weiß der Parser wann er anfängt zu parsen.
Hast du das mit dem Frontend Abgesprochen, das für ein input, ein RootElement gesendet wird und kein inputElement?
Die Root muss dann den path der inputDatei halten, was nicht vorgesehen ist im RootElement und die Root wurde auch als SingletonPAttern entworfen, das muss dann noch geändert werden.

**Comment by MaddnRuleZ** [comment]
(1) der Parser Speichert alles, auch dinge die vor dem /startDocument kommen, kann ja nicht sein dass die Daten verloren gehen durch benutzung unseres Programms

(2) Nein, noch nicht muss das mal mit denen Besprechn, sollte denen auch von nuzten sein
(3) Glaube nicht dass wir die doc anpassen müssen, aufjedenfall jetzt noch nicht

**Comment by svMahler** [comment]
zu (1): Woher erkennt der Parser aber um was für ein Dokument es sich handelt?
Hauptdokument:
Header
\begin{documnet}
body
\end{document}
---
InputFile:
Body
----
Dein Parser muss ja den Header abspeichern und erst ab begin anfangen zu Parsen, aber das input Dokument hat das nicht.

zu (2):
Mach das lieber frühzeitig

Wie stellst du dir das zurückübersetztn in LaTeX-Code vor die Root übernimmt das Schreiben von begin und end. Die Input file hat aber ganz andere LaTeX-Befehle, wie willst du das automatisch erkennen? 

Eine root hat auch keine Parents, input schon.

Ich verstehe ehrlich gesagt den Vorteil nicht aus dem Input ein Root zu machen, was sparst du dir dabei? Ich denke im Nachhinein muss man ziemlich viele Fallunterscheidungen machen um aus der Root erkennen zu können, dass es ein Input war.
