### ISSUE TITLE
CommandHandler

### ISSUE THREAD

**Issue by svMahler** [MaddnRuleZ/Tree#3]
return value of Response in processCommand: JsonNode or String?

**Comment by svMahler** [comment]
Ja, also ein String, der wie im Entwurfsheft bei der internen Kommunikation aussieht. Mir wäre ein JsonNode lieber, aber ich kann auch den String entgegennehmen.

**Comment by MaddnRuleZ** [comment]
Also mir ist das Egal, musst halt nur sagen was du brauchst.
wir müssen uns ja nicht zusehr an den entwurf halten, wenn wir bessere Implementierungen finden
